### ISSUE TITLE
[Drive V3] java.net.ProtocolException: DELETE does not support writing (Android <= 19)

### ISSUE THREAD

**Issue by Pourqavam** [googleapis/google-api-java-client-services#10870]
Hi
The delete file request of the Drive V3 API throws exception on Android <= 4.4:
```
java.net.ProtocolException: DELETE does not support writing
at com.android.okhttp.internal.http.HttpURLConnectionImpl.initHttpEngine(HttpURLConnectionImpl.java:258)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:86)
at com.android.okhttp.internal.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:161)
at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:151)
at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:84)
at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1012)
at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:514)
at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455)
at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
```
https://stackoverflow.com/questions/10338615/sending-http-delete-request-in-android

**Comment by lesv** [comment]
[Drive support](https://developers.google.com/drive/api/v3/support) is on StackOverflow.
