### ISSUE TITLE
codegen job has been failing

### ISSUE THREAD

**Issue by suztomo** [googleapis/google-api-java-client-services#13409]
<img width="1338" alt="Screen Shot 2022-08-01 at 9 18 15 AM" src="https://user-images.githubusercontent.com/28604/182156806-94353d16-81be-4e14-a242-0efb6d769e95.png">

```
TypeError: Cannot read property 'error' of undefined
    at Object.getChanges (/home/runner/work/_actions/googleapis/code-suggester/v2/action/webpack:/build/src/bin/handle-git-dir-change.js:190:1)
    at run (/home/runner/work/_actions/googleapis/code-suggester/v2/action/dist/index.js:12908:56)
    at /home/runner/work/_actions/googleapis/code-suggester/v2/action/dist/index.js:12975:5
    at /home/runner/work/_actions/googleapis/code-suggester/v2/action/dist/index.js:12978:3
    at Object.<anonymous> (/home/runner/work/_actions/googleapis/code-suggester/v2/action/dist/index.js:12981:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
```

**Comment by suztomo** [comment]
Now it's failing with an invalid Python version.

<img width="1009" alt="Screen Shot 2022-11-28 at 11 50 59 AM" src="https://user-images.githubusercontent.com/28604/204335314-a3793ddb-dd95-4164-af77-1c3014d2c527.png">

**Comment by suztomo** [comment]
Asked https://github.com/googleapis/discovery-artifact-manager/issues/6142 .

**Comment by alicejli** [comment]
Fixed with https://github.com/googleapis/discovery-artifact-manager/pull/6315
