### ISSUE TITLE
Google HomeGraph requestResync return status 500

### ISSUE THREAD

**Issue by kalwinskidawid** [googleapis/google-api-java-client-services#20960]
Hey,
I have a problem with `resync request` send via HomeGraph dependency.
The problem is that your service returns error `500`, but the `SYNC` from agentUserId goes out correctly. I've checked my request - it looks okay, moreover I receive `SYNC` from that agentUserId but your server's endpoint return wrong status code. Could you check it? 
I use `com.google.apis:google-api-services-homegraph:v1-rev20230707-2.0.0`
#### Code example

```java
    public GoogleCredentials getCredentials() throws IOException {
        return this.googleServiceConfiguration.googleCredentials()
                .createScoped(List.of("https://www.googleapis.com/auth/homegraph"));
    }

    public HomeGraphService getHomeGraphService() throws GeneralSecurityException, IOException {
        return new HomeGraphService.Builder(
                GoogleNetHttpTransport.newTrustedTransport(),
                GsonFactory.getDefaultInstance(),
                new HttpCredentialsAdapter(this.getCredentials()))
                .setApplicationName("HomeGraphExample/1.0")
                .build();
    }

    public RequestSyncDevicesResponse requestToRereadDevicesByAgentUser(final String agentUserId) throws GeneralSecurityException, IOException {
        final RequestSyncDevicesRequest request = new RequestSyncDevicesRequest().setAgentUserId(agentUserId).setAsync(false);
        return this.getHomeGraphService().devices().requestSync(request).execute();
    }
```

#### Stack trace
```
com.google.api.client.googleapis.json.GoogleJsonResponseException: 500 Internal Server Error
POST https://homegraph.googleapis.com/v1/devices:requestSync
{
  "code": 500,
  "errors": [
    {
      "domain": "global",
      "message": "Internal error encountered.",
      "reason": "backendError"
    }
  ],
  "message": "Internal error encountered.",
  "status": "INTERNAL"
}
        at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146) ~[google-api-client-1.33.0.jar!/:1.33.0]
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118) ~[google-api-client-1.33.0.jar!/:1.33.0]
        at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:37) ~[google-api-client-1.33.0.jar!/:1.33.0]
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:428) ~[google-api-client-1.33.0.jar!/:1.33.0]
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1111) ~[google-http-client-1.42.3.jar!/:1.42.3]
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:514) ~[google-api-client-1.33.0.jar!/:1.33.0]
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455) ~[google-api-client-1.33.0.jar!/:1.33.0]
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565) ~[google-api-client-1.33.0.jar!/:1.33.0]
        at net.auth.service.google.home.action.GoogleHomeGraphService.requestToRereadDevicesByAgentUser(GoogleHomeGraphService.java:50) ~[!/:0.0.1-SNAPSHOT]
```

**Comment by suztomo** [comment]
The 500 Internal Server Error seems not caused by the client library. API reference document is at https://developers.home.google.com/reference/home-graph/rpc.

Would you follow its support page https://developers.home.google.com/cloud-to-cloud/support ?
