### ISSUE TITLE
Native compilation with GraalVM

### ISSUE THREAD

**Issue by ValTheBoss** [googleapis/google-api-java-client-services#23642]
There is an issue when using native compilation with GraalVM. I'm trying to use the **Admin SDK API Client Library** for directory operations. 

#### Environment details

- Admin SDK API Client Library, version _directory_v1-rev20240924-2.0.0_
- Java Temurin 21
- Native compilation of a _Spring Boot 3.3.4_ app using by default at this time : 
  - paketo-buildpacks/ca-certificates   3.8.6
  - paketo-buildpacks/bellsoft-liberica 10.9.0
  - paketo-buildpacks/syft              2.1.0
  - paketo-buildpacks/executable-jar    6.11.3
  - paketo-buildpacks/spring-boot       5.31.2
  - paketo-buildpacks/native-image      5.14.4

#### Steps to reproduce

Fresh **Spring Boot 3.3.4** project.

**Maven configuration**
```xml
<dependency>
  <groupId>com.google.apis</groupId>
  <artifactId>google-api-services-admin-directory</artifactId>
  <version>directory_v1-rev20240924-2.0.0</version>
</dependency>
...
<plugin>
  <groupId>org.graalvm.buildtools</groupId>
  <artifactId>native-maven-plugin</artifactId>
</plugin>
```

**Build Directory service**

```java
private Directory buildDirectoryService(@Nonnull final String gcpKey, @Nonnull final String serviceAccountUser) throws IOException, GeneralSecurityException {
    final ServiceAccountCredentials sourceCredentials =
        ServiceAccountCredentials.fromStream(...)
        .toBuilder()
        .setServiceAccountUser(serviceAccountUser)
        .setScopes(ImmutableSet.of(
            DirectoryScopes.ADMIN_DIRECTORY_GROUP_READONLY,
            DirectoryScopes.ADMIN_DIRECTORY_USER_READONLY
        ))
        .build();

    return new Directory.Builder(Utils.getDefaultTransport(), Utils.getDefaultJsonFactory(), new HttpCredentialsAdapter(sourceCredentials))
        .setApplicationName("MY_APP")
        .build();
  }
```

**Add reflection hints for ErrorInfo.class**
```java
@Configuration
@ImportRuntimeHints(NativeImageHints.class)
class NativeImageHints implements RuntimeHintsRegistrar {
  @Override
  public void registerHints(RuntimeHints hints, ClassLoader classLoader) {
    hints.reflection().registerType(ErrorInfo.class, (type) -> type.withConstructor(Collections.emptyList(), ExecutableMode.INVOKE));
  }
}
```

**Directory api call**
```java
final Users batch = directory
            .users()
            .list()
            .setMaxResults(100)
            .setDomain("my-domain.com")
            .execute();
```

**Build and run image**
```shell
mvn clean spring-boot:build-image -e --no-transfer-progress -P native -D skipTests=true
docker run -p 8080:8080 my-app:0.0.1-SNAPSHOT
```

**Result of directory execute()**
```
2024-10-14T12:44:13.891Z  INFO 1 --- [my-app] [nio-8080-exec-1] c.google.api.client.http.HttpTransport   : {
  "error": {
    "code": 400,
    "message": "Bad Request",
    "errors": [
      {
        "message": "Bad Request",
        "domain": "global",
        "reason": "badRequest"
      }
    ]
  }
}
```

**Reason**
If I launch the app in DEBUG logging mode, I can see that the URL for the API query is not properly prepared : 
```
curl -v --compressed 
-H 'Accept-Encoding: gzip' 
-H 'Authorization: <Not Logged>' 
-H 'User-Agent: MY_APP Google-API-Java-Client/2.7.0 Google-HTTP-Java-Client/1.45.0 (gzip)' 
-H 'x-goog-api-client: gl-java/21.0.4-graalvm gdcl/2.7.0 linux/6.8.0' -- 'https://admin.googleapis.com/admin/directory/v1/users'
```

instead of

```
curl -v --compressed 
-H 'Accept-Encoding: gzip' 
-H 'Authorization: <Not Logged>' 
-H 'User-Agent: MY_APP Google-API-Java-Client/2.7.0 Google-HTTP-Java-Client/1.45.0 (gzip)' 
-H 'x-goog-api-client: gl-java/21.0.4-graalvm gdcl/2.7.0 linux/6.8.0' -- 'https://admin.googleapis.com/admin/directory/v1/users?domain=my-domain.com&maxResults=100'
```

**Comment by diegomarquezp** [comment]
Thanks for reporting this @ValTheBoss. It's certainly strange that the parameters don't get sent in the native image. Do you have by any chance the reproducer project handy so we can look into it?
Also, for faster response times, please refer to our [support hub](https://cloud.google.com/support-hub/).

@Phakrada666, looks like you are sharing the dependencies listed in the bug as well. Are you also running into the same issue?

**Comment by reza-cb** [comment]
Any updates on this issue? I am encountering the same problem when using google-api-services-sheets (v4-rev20241008-2.0.0) to read a spreadsheet.

Here is the code snippet:
```
final var sheetValues = sheetsService.spreadsheets().values()
        .get(spreadsheetId, "Teacher!A:C")
        .execute();
```
This returns the following error:
<p>The requested URL <code>/v4/spreadsheets//values/</code> was not found on this server.  <ins>That’s all we know.</ins>

	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:37)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$3.interceptResponse(AbstractGoogleClientRequest.java:479)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1111)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:565)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:506)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:616)
	
I suspect the issue might be related to the URL construction, particularly the double slashes (//) in the endpoint. Could you please advise if this is a bug or if I need to adjust my implementation?

The same code works fine on JVM but fails on GraalVM

**Comment by ldetmer** [comment]
@ValTheBoss are you still seeing this issue, could you please provide a reproducer project for us to look into?
