### ISSUE TITLE
Compilation failed with the latest R8 Shrinker - google-api-services-safebrowsing:v4-rev20190923-1.30.3'

### ISSUE THREAD

**Issue by eakteam** [googleapis/google-api-java-client-services#3258]
AGPBI: {"kind":"error","text":"Library class android.net.http.AndroidHttpClient implements program class org.apache.http.client.HttpClient","sources":[{}],"tool":"R8"}

Please refer to this bug : https://issuetracker.google.com/issues/146620827

To initialize this lib i do something like this :

httpTransport = NetHttpTransport.Builder().build()
val safebrowsingBuilder = Safebrowsing.Builder(httpTransport, GOOGLE_JSON_FACTORY, null).setApplicationName(GOOGLE_APPLICATION_NAME)

NetHttpTransport is referenced from
import com.google.api.client.http.javanet.NetHttpTransport

I tried to migrate HttpTransport too to :

httpTransport = GoogleNetHttpTransport.newTrustedTransport()
but still crashes, something is not going OK with this lib ? Any workaround ?

**Comment by eakteam** [comment]
as workaround i have solved R8 crash by adding this to my build.gradle (please note that the part `useLibrary 'org.apache.http.legacy'` i have completely disabled)

```
implementation ('com.google.apis:google-api-services-safebrowsing:v4-rev20190923-1.30.3') {
        exclude module: 'commons-logging'
        exclude module: 'httpcore'
        exclude module: 'httpclient'
}
```

So, after this it is working OK in debug build and the R8 is not failing anymore in release build, but i got a new crash when trying to access that feature :

Also i tried to add but it still crashes:

```
-keep class com.google.api.services.safebrowsing.** { *; }
-keep class io.grpc.** {*;}
```

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Package.getImplementationVersion()' on a null object reference
       at com.google.api.client.http.HttpRequest.getVersion(HttpRequest.java:1207)
       at com.google.api.client.http.HttpRequest.<clinit>(HttpRequest.java:57)
       at com.google.api.client.http.HttpTransport.buildRequest(HttpTransport.java:115)
       at com.google.api.client.http.HttpRequestFactory.buildRequest(HttpRequestFactory.java:86)
       at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.buildHttpRequest(AbstractGoogleClientRequest.java:422)
       at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:541)
       at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:474)
       at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:591)
       at com.eakteam.networkmanager.fragments.url_check_safe_browsing$filloSkaniminSafeBrowsingAPI$1.invokeSuspend(url_check_safe_browsing.java:302)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:56)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:561)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:727)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:667)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:655)
```

**Comment by eakteam** [comment]
OK, so refers to 2nd comment i tried also those rules : https://github.com/google/google-api-java-client-samples/blob/master/tasks-android-sample/proguard-google-api-client.txt

```
-keepattributes *Annotation*,Signature,InnerClasses,EnclosingMethod,SourceFile,LineNumberTable
-keepclassmembers class * {
  @com.google.api.client.util.Key <fields>;
}

```
It still doesn't helps, but if write this global rule it works OK but the size of app increases

`-keep class com.google.api.** { *; }`

So to sum things up it seems to have 2 issues.

> 1) Apache things should be removed because R8 doesn't support anymore
> 2) Default proguard rules suggested are not working

**Comment by eakteam** [comment]
Triage me... What means ?

**Comment by codyoss** [comment]
As pointed out in the other issue tracker, that last issue you are having is fixed in master. There will be new releases of this lib as soon as next week.
