### ISSUE TITLE
java.net.UnknownHostException: www.googleapis.com or oauth2.googleapis.com

### ISSUE THREAD

**Issue by GuilhermeViterboGalvao** [googleapis/google-api-java-client-services#9387]
#### Environment details

  - Programming language: Java
  - OS: Raspberry Pi OS Lite (32-Bit)
  - Language runtime version: 1.8.0_241
  - Package version: 1.31.5

#### Steps to reproduce

I'm running my java code into a Raspberry Pi 3 B+, and I'm using the google-api-client version 1.31.5.

Basically, my code uploads a file after each one minute to a Google Driver folder. At the beginning of a new day, I upload a big file and remove the chunks into a Google Drive folder.

The problem just happens after a few days (like 3 or 4 days), after my code running.

After a while, I start getting the error java.net.UnknownHostException (for hosts www.googleapis.com or oauth2.googleapis.com).

I'll put here peace of the stack trace:

2021-08-07 07:48:10 ERROR GoogleDriveFacade:224 - oauth2.googleapis.com
java.net.UnknownHostException: oauth2.googleapis.com
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:289)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1367)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1342)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:246)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:113)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:84)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1012)
	at com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:304)
	at com.google.api.client.auth.oauth2.TokenRequest.execute(TokenRequest.java:324)
	at com.google.api.client.auth.oauth2.Credential.executeRefreshToken(Credential.java:547)
	at com.google.api.client.auth.oauth2.Credential.refreshToken(Credential.java:470)
	at com.google.api.client.auth.oauth2.Credential.intercept(Credential.java:201)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:880)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:514)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:455)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
	at br.com.gvg.dvrtogoogledrive.facade.google.GoogleDriveFacade.buildQuery(GoogleDriveFacade.java:221)
	at br.com.gvg.dvrtogoogledrive.facade.google.GoogleDriveFacade.getFolderByName(GoogleDriveFacade.java:203)
	at br.com.gvg.dvrtogoogledrive.facade.google.GoogleDriveFacade.createFolderOnGoogleDrive(GoogleDriveFacade.java:155)
	at br.com.gvg.dvrtogoogledrive.facade.google.GoogleDriveFacade.upload(GoogleDriveFacade.java:113)
	at br.com.gvg.dvrtogoogledrive.thread.FfmpegConcatChunks.execute(FfmpegConcatChunks.java:55)
	at br.com.gvg.dvrtogoogledrive.thread.FfmpegBaseThread.run(FfmpegBaseThread.java:36)

This raspberry pi has 1 GB of RAM and a processor with 1.4 GHz and 4 cores.

I already checked my API rate limit, but I never get close to reaching the usage limit.

Also, I limited my JVM usage RAM limit using the args -Xms512m -Xmx512m.

To be honest, I really don't know if this could be a problem with the SDK, but I don't know what else to do.

If one of you guys could help me to understand this strange behavior, I'll be very thankful.

**Comment by GuilhermeViterboGalvao** [comment]
I found the problem!
As I mentioned before, I didn't believe that this could be a problem related to de SDK, but even so, I decided to open this issue to see if anyone could help me with that.
To find the root cause of the problem I added the param -XX:HeapDumpPath.
Analyzing the dump, I realize that what was causing this problem was a thread that was writing a log file and wasn't releasing a StringBuilder to be collected for the garbage collector. Because of that, my application started to consume a lot of memory and causing memory exhaustion on OS.
When we have this scenario the OS get started having a few problems with other programs that need a few memory free space to execute his routines. One collateral effect was my OS wasn't not more be able the resolve some DNSs.
