### ISSUE TITLE
Conflict with Google Cloud Storage

### ISSUE THREAD

**Issue by ShaimaaSabry** [googleapis/google-api-java-client-services#9749]
I have google cloud storage and kms in my backend application:
```
<dependency>
	<groupId>com.google.cloud</groupId>
	<artifactId>google-cloud-storage</artifactId>
	<version>1.77.0</version>
</dependency>
<dependency>
	<groupId>com.google.cloud</groupId>
	<artifactId>google-cloud-kms</artifactId>
	<version>1.0.0</version>
</dependency>
```
Recently I needed to add android publisher:
```
<dependency>
    <groupId>com.google.apis</groupId>
    <artifactId>google-api-services-androidpublisher</artifactId>
    <version>v3-rev139-1.25.0</version>
</dependency>
```
Now google cloud storage breaks with the following error:
```
java.lang.ExceptionInInitializerError: null
	at com.google.api.services.storage.Storage$Builder.build(Storage.java:11194)
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.<init>(HttpStorageRpc.java:122)
	at com.google.cloud.storage.StorageOptions$DefaultStorageRpcFactory.create(StorageOptions.java:55)
	at com.google.cloud.storage.StorageOptions$DefaultStorageRpcFactory.create(StorageOptions.java:49)
	at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:560)
	at com.google.cloud.storage.StorageOptions.getStorageRpcV1(StorageOptions.java:121)
	at com.google.cloud.storage.StorageImpl.<init>(StorageImpl.java:124)
	at com.google.cloud.storage.StorageOptions$DefaultStorageFactory.create(StorageOptions.java:45)
	at com.google.cloud.storage.StorageOptions$DefaultStorageFactory.create(StorageOptions.java:39)
	at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:540)
	at
```
When I remove the android publisher dependency, the storage works fine. Please advise.

**Comment by meltsufin** [comment]
Obsolete. Please try the newer versions of all dependencies.
